//Gen data
const generations = [
    {
      year: "7E4",
      name: "Zehner",
      memory: 32000,
      programSpace: 0,
      frameSpace: 298,
      currentPerLed: 0.012,
      baseCurrent: 0.020,
      core: "arduino",
      fqbn: "arduino:avr:pro",
      animationCount: 4,
      layout: 7,
    },
    {
      year: "7E5",
      name: "Glitzh",
      memory: 32000,
      programSpace: 0,
      frameSpace: 298,
      currentPerLed: 0.012,
      baseCurrent: 0.040,
      core: "arduino",
      fqbn: "arduino:avr:micro",
      animationCount: 4,
      layout: 7,
    },
    {
      year: "7E6",
      name: "Lümen",
      memory: 1318001,
      programSpace: 0,
      frameSpace: 396,
      currentPerLed: 0.012,
      baseCurrent: 0.200,
      core: "esp32",
      fqbn: "esp32:esp32:lolin32-lite",
      animationCount: 16,
      layout: 7,
    },
    {
      year: "7E7",
      name: "Gauß",
      memory: 2522801    ,
      programSpace: 0,
      frameSpace: 396,
      currentPerLed: 0.012,
      baseCurrent: 0.200,
      core: "esp32",
      fqbn: "esp32:esp32:lolin32-lite",
      animationCount: 16,
      layout: 7,
    },
    {
      year: "7E8",
      name: "Fritz",
      memory: 2522801,
      programSpace: 0,
      frameSpace: 396,
      currentPerLed: 0.005,
      baseCurrent: 0.200,
      core: "esp32",
      fqbn: "esp32:esp32:lolin32-lite",
      animationCount: 16,
      layout: 7,
    },
  ]

  export default generations;